version: '3'

# Services: 
  # db
  # app
  # psql-command

services:
  db:
    image: postgres:latest
    restart: always
    volumes:
      - ./data:/var/lib/postgresql/data
    networks:
      - bridge

  app:
    build:
      context: .
      dockerfile: dockerfile
    restart: always
    ports:
      - "3000:3000"
    depends_on:
      - db

    networks:
      - bridge

  psql-command:
    image: postgres:latest
    restart: always
    depends_on:
      - db
    networks:
      - bridge
      
networks:
  bridge:
    driver: bridge